### ISSUE TITLE
Panel issue

### ISSUE THREAD

**Issue by cschol** [terrytheplatypus/Plurm#1]
Plugin panel shows transparent when loaded in Rack:

![Plurm](https://user-images.githubusercontent.com/624427/116016025-95e1ae80-a5f8-11eb-98b1-e8833f2b9482.png)

**Comment by terrytheplatypus** [comment]
That was intentional, I could change it to opaque if that's necessary.

**Comment by cschol** [comment]
OK. That's fine with me. The only issue is that the module browser does not support transparency and it will show black there.

![image](https://user-images.githubusercontent.com/624427/116156244-71dda600-a6a8-11eb-9569-859c420e4bea.png)

Let me know if you want to change it or leave it as is.

**Comment by terrytheplatypus** [comment]
yeah i'm fine with that.
